version: '3.9'

services:
  postgres:
    image: storefront
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  postgres-test:
    image: storefront
    ports:
      - '5433:5432'
    env_file:
      - .env

volumes:
  postgres: