version: 2.1
orbs: 
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run: npx -p typescript tsc --init
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: yarn && yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
        image: ubuntu-2004:202201-02
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: Wait for Database Port
          command: while ! nc -z 127.0.0.1 5432 ; do sleep 1 ; done
      - run: npm run migrate
      - run: yarn deploy
workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build